# Generated by Django 3.1.8 on 2021-06-02 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Superheros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='catch_phrase',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
